name: Build & Test
run-name: ${{ github.actor }} new push/pull_request build and test Turtle
on: [push, pull_request]
jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v3
      - name: Install Environment
        run: sh ./setup/setup.sh
      - name: Setup default MySQL
        run: sudo mysql < ./setup/setup.sql
      - name: Show CMake Version
        run: cmake --version
      - name: Build and Test Turtle
        run: mkdir build && cd build && cmake .. && make && make test